site_title = "MyArxiv"
limit_days = 7
cache_url = "https://hotung1027.github.io/MyArxiv/cache.json"

[[sources]]
limit = 5
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 20
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 20
category = "eess.IV"
title = "Image and Video Processing"

[[sources]]
limit = 20
category = "cs.GR"
title = "Graphics"

[[sources]]
limit = 20
category = "eess.SP"
title = "Signal Processing"



[[sources]]
limit = 20
category = "cs.CG"
title = "Computational Geometry"

[[sources]]
limit = 10
category = "cs.DS"
title = "Data Structure and Algorithm"

[[sources]]
limit = 20
category = "cs.GT"
title = "Game Theory"

[[sources]]
limit = 20
category = "cs.IT"
title = "Information Theory"

[[sources]]
limit = 20
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 20
category = "cs.DM"
title = "Discrete Mathematics"

[[sources]]
limit = 20
category = "cs.SC"
title = "Symbolic Computation"

[[sources]]
limit = 20
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 20
category = "cs.AI"
title = "Artificial Intelligence Learning"

# Robotics 
[[sources]]
limit = 20
category = "cs.SY"
title = "Systems and Control"

[[sources]]
limit = 20
category = "eess.SY"
title = "Systems and Control"


[[sources]]
limit = 20
category = "cs.RO"
title = "Robotics"


[[sources]]
limit = 20
category = "cs.AR"
title = "Hardware Architecture"



[[sources]]
limit = 20
category = "q-fin.CP"
title = "Computational Finance"

[[sources]]
limit = 20
category = "q-fin.MF"
title = "Mathematical Finance"


[[sources]]
limit = 20
category = "q-fin.PM"
title = "Portfolio Management"


[[sources]]
limit = 20
category = "q-fin.SF"
title = "Statistical Finance"





[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
